image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

variables:
  DOTNET_ROOT: "/root/.dotnet"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

cache:
  paths:
    - .nuget/

before_script:
  - 'dotnet restore'

build:
  stage: build
  script:
    - 'dotnet build'

test:
  stage: test
  script:
    - 'dotnet test'